name: solarpark
path: /Users/justicealuu/research_project/perovskite_segment/data/solarpark
batch_size: 16
image_size: 256
aug_rot_angle: 15

# Normalization Statistics

mean:
  - 0.78825041
  - 0.3565332
  - 0.2667081

std:
  - 0.25891912
  - 0.31241968
  - 0.24355275
